from abc import ABC, abstractmethod
from typing import Generator, Dict, List

class LLMError(Exception):
    """Base exception class for all LLM Client failures."""
    pass

class LLMClient(ABC):
    """Abstract base class representing an LLM Client interface."""

    @abstractmethod
    def stream_chat(self, messages: List[Dict[str, str]]) -> Generator[str, None, None]:
        """
        Sends a conversation history to the model and streams back the responses.

        Args:
            messages: A list of message dictionaries, e.g. [{"role": "user", "content": "hi"}]

        Yields:
            Token chunks generated by the assistant.

        Raises:
            LLMError: If any provider-specific network or API errors occur.
        """
        pass
